---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: stream-storage-coordinator
  namespace: $NAMESPACE
  labels:
    app: stream-storage-coordinator
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: stream-storage-coordinator
