apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: stream-api
provisioner: kubernetes.io/aws-ebs
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  type: gp3
  fsType: ext4
  throughput: "270"
  encrypted: "true"
  allowAutoIOPSPerGBIncrease: "true"

