project_name: "kbc"
dist: "target"
builds:
  - main: "./src/main.go"
    binary: "kbc"
<<<<<<< HEAD
    goos: ["linux", "windows", "darwin"]
=======
    goos: ["linux", "darwin", "windows"]
>>>>>>> efd3418 (Upload packages to S3)
    goarch: ["amd64", "arm", "arm64"]
    goarm: ["6"]
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X keboola-as-code/src/build.BuildVersion={{ if index .Env "TARGET_VERSION"  }}{{ .Env.TARGET_VERSION }}{{ else }}dev{{ end }}
      - -X keboola-as-code/src/build.BuildDate={{.Date}}
      - -X keboola-as-code/src/build.GitCommit={{.Commit}}
    hooks:
      # Copy binary to TARGET_PATH if set
      post: '{{ if index .Env "TARGET_PATH"  }}cp "{{ .Path }}" "{{ .Env.TARGET_PATH }}"{{ else }}true{{ end }}'

changelog:
  skip: true

archives:
  - id: archives
    files:
      - none*
    format: zip
    format_overrides:
      - goos: darwin
        format: binary

snapshot:
  name_template: '{{ if index .Env "SNAPSHOT"  }}{{ .Env.SNAPSHOT }}{{ else }}dev{{ end }}'

nfpms:
  - id: packages
    vendor: Keboola
    homepage: https://keboola.com
    maintainer: Keboola <support@keboola.com>
    description: Keboola Connection CLI client.
    license: MIT
    bindir: /usr/bin
    formats:
      - apk
      - deb
      - rpm
<<<<<<< HEAD
=======
    rpm:
      signature:
        key_file: '{{ if index .Env "GPG_PRIVATE_PATH"  }}{{ .Env.GPG_PRIVATE_PATH }}{{ end }}'
    deb:
      signature:
        key_file: '{{ if index .Env "GPG_PRIVATE_PATH"  }}{{ .Env.GPG_PRIVATE_PATH }}{{ end }}'
    apk:
      signature:
        key_name: keboola
        key_file: '{{ if index .Env "ALPINE_PRIVATE_KEY_PATH"  }}{{ .Env.ALPINE_PRIVATE_KEY_PATH }}{{ end }}'

publishers:
  - name: Upload artifacts to S3
    cmd: ./scripts/pkgs/publish-to-s3.sh "{{ abs .ArtifactPath }}" "{{ .ArtifactName }}" "{{ .ProjectName }}" "{{ .Version }}" "{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    ids:
      - archives
      - packages

release:
  ids:
    - archives
    - packages
>>>>>>> efd3418 (Upload packages to S3)
