project_name: "keboola-as-code"

dist: target
builds:
  - main: "./src/main.go"
    id: kbc
    binary: "kbc"
    goos: ["linux", "darwin", "windows"]
    goarch: ["amd64", "arm", "arm64"]
    goarm: ["6", "7"]
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X keboola-as-code/src/build.BuildVersion={{ if index .Env "TARGET_VERSION"  }}{{ .Env.TARGET_VERSION }}{{ else }}dev{{ end }}
      - -X keboola-as-code/src/build.BuildDate={{.Date}}
      - -X keboola-as-code/src/build.GitCommit={{.Commit}}
# changelog:
#   sort: "asc"
#   filters:
#     exclude: ["^docs:", "^test:", "Merge pull request", "Merge branch"]

archives:
  - format_overrides:
      - goos: "windows"
        format: "zip"
    id: kbc
    files:
      - none*
    builds:
      - kbc
    name_template: "kbc-v{{ .Version }}-{{ .Os }}_{{ .Arch }}"
    replacements:
      amd64: 64-bit
      "386": 32-bit
      darwin: macOS
      linux: linux
