project_name: "keboola-as-code"

dist: target
builds:
  - main: "./src/main.go"
    id: kbc
    binary: "kbc"
    goos: ["linux", "darwin", "windows"]
    goarch: ["amd64", "arm", "arm64"]
    goarm: ["6"]
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X keboola-as-code/src/build.BuildVersion={{ if index .Env "TARGET_VERSION"  }}{{ .Env.TARGET_VERSION }}{{ else }}dev{{ end }}
      - -X keboola-as-code/src/build.BuildDate={{.Date}}
      - -X keboola-as-code/src/build.GitCommit={{.Commit}}
    ignore:
      - goos: windows
        goarch: arm64

changelog:
  # Set it to true if you wish to skip the changelog generation.
  # This may result in an empty release notes on GitHub/GitLab/Gitea.
  skip: true

archives:
  - format_overrides:
      - goos: "windows"
        format: "zip"
    id: kbc
    # dont package README and LICENSE files to the release archive
    files:
      - none*
    builds:
      - kbc
    name_template: "kbc-v{{ .Version }}-{{ .Os }}_{{ .Arch }}"
    replacements:
      amd64: 64-bit
      "386": 32-bit
      darwin: macOS
      linux: linux

snapshot:
  # Allows you to change the name of the generated snapshot
  #
  # Note that some pipes require this to be semantic version compliant (nfpm,
  # for example).
  #
  # Default is `{{ .Version }}-SNAPSHOT-{{.ShortCommit}}`.
  name_template: "{{ incpatch .Version }}-devel"
