version: '3'
services:
  dev:
    image: keboolabot/keboola-as-code-dev
    build: .
    volumes:
      - ./:/code:z
      - cache:/tmp/cache
    environment:
      - TEST_PROJECT_ID
      - TEST_KBC_STORAGE_API_HOST
      - TEST_KBC_STORAGE_API_TOKEN

volumes:
  cache:
