version: '3'
services:
  dev:
    image: keboolabot/keboola-as-code-dev
    build:
      context: .
      dockerfile: ./provisioning/dev/docker/Dockerfile
    links:
      - etcd
    volumes:
      - ./:/code:z
      - cache:/tmp/cache
    environment:
      # For all
      - TEST_KBC_PROJECTS
      # For Templates API
      - KBC_STORAGE_API_HOST
      # For Buffer API
      - KBC_BUFFER_API_HOST=buffer.keboola.local
      # Disable DataDog integration
      - DATADOG_ENABLED=false
      # Etcd for the Templates API
      - TEMPLATES_API_ETCD_ENABLED=true
      - TEMPLATES_API_ETCD_ENDPOINT=etcd:2379
      - TEMPLATES_API_ETCD_USERNAME=root
      - TEMPLATES_API_ETCD_PASSWORD=toor
      - TEMPLATES_API_ETCD_NAMESPACE=templates-api
      # Etcd for the Buffer API and Worker
      - BUFFER_ETCD_ENDPOINT=etcd:2379
      - BUFFER_ETCD_USERNAME=root
      - BUFFER_ETCD_PASSWORD=toor
      - BUFFER_ETCD_NAMESPACE=buffer
    ports:
      - "8000:8000"
      - "6060:6060"
  # Same etcd is used for all services, but with different namespace
  etcd:
    hostname: etcd
    image: docker.io/bitnami/etcd:3.5.5-debian-11-r16
    environment:
      ALLOW_NONE_AUTHENTICATION: "no"
      ETCD_NAME: "etcd"
      ETCD_ROOT_PASSWORD: "toor"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd:2379"
      ETCD_INITIAL_ADVERTISE_PEER_URLS: "http://etcd:2380"
      ETCD_INITIAL_CLUSTER_TOKEN: "cluster"
      ETCD_INITIAL_CLUSTER": "default=http://etcd:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_LISTEN_PEER_URLS: "http://0.0.0.0:2380"
      ETCD_DISABLE_STORE_MEMBER_ID: "true"

volumes:
  cache:
