version: '3'
services:
  dev:
    image: keboolabot/keboola-as-code-dev
    build: .
    links:
      - etcd
    volumes:
      - ./:/code:z
      - cache:/tmp/cache
    environment:
      # For CLI
      - TEST_KBC_PROJECTS
      ## OR
      - TEST_KBC_PROJECT_ID
      - TEST_KBC_STORAGE_API_HOST
      - TEST_KBC_STORAGE_API_TOKEN
      # For Templates API
      - KBC_STORAGE_API_HOST
      # Disable DataDog integration
      - DATADOG_ENABLED=false
      # Etcd
      - ETCD_ENABLED=true
      - ETCD_ENDPOINT=etcd:2379
      - ETCD_USERNAME=root
      - ETCD_PASSWORD=toor
    ports:
      - "8000:8000"
      - "6060:6060"
  etcd:
    image: docker.io/bitnami/etcd:3.5.4-debian-11-r27
    environment:
      ALLOW_NONE_AUTHENTICATION: "no"
      ETCD_ROOT_PASSWORD: "toor"

volumes:
  cache:
