name: 'Load Docker image'
description: 'Load Docker image'
runs:
  using: "composite"
  steps:
    - name: Docker login
      run: docker login --username "$DOCKERHUB_USER" --password "$DOCKERHUB_TOKEN"
      shell: bash
    - name: Pull image
      run: |
        docker pull ${{ env.IMAGE }}:$IMAGE_TAG
        docker tag ${{ env.IMAGE }}:$IMAGE_TAG ${{ env.IMAGE }}:latest
      shell: bash
