name: 'Load Docker image'
description: 'Load Docker image'
runs:
  using: "composite"
  steps:
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKERHUB_USER }}
        password: ${{ env.DOCKERHUB_TOKEN }}
    - name: Pull image
      run: |
        docker pull ${{ env.IMAGE }}:$IMAGE_TAG
        docker tag ${{ env.IMAGE }}:$IMAGE_TAG ${{ env.IMAGE }}:latest
      shell: bash
