apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-csas-redirector
  namespace: $NAMESPACE
  labels:
    app: apps-proxy
spec:
  replicas: $CSAS_MIGRATION_APPS_PROXY_REDIRECT_REPLICAS
  selector:
    matchLabels:
      app: apps-proxy
  template:
    metadata:
      labels:
        app: apps-proxy
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        ports:
        - containerPort: 8000
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config
