name: 'Release CLI'
description: 'Release CLI to AWS bucket'
inputs:
  tag:
    description: Tag version
    required: true
  version:
    description: Version
    required: true
  github_token:
    description: Github token.
    required: true
  apple_account_password:
    description: Apple account password
    required: true
runs:
  using: "composite"
  steps:
    - name: Release
      shell: bash
      run: task release
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        CLI_DIST_BASE_URL: "https://cli-dist.keboola.com"
        DEB_KEY_PRIVATE_PATH: /tmp/keys/deb.key
        RPM_KEY_PRIVATE_PATH: /tmp/keys/rpm.key
        APK_KEY_PRIVATE_PATH: /tmp/keys/apk.key
        APPLE_ACCOUNT_PASSWORD: ${{ inputs.apple_account_password }}
        VERSION: ${{ inputs.version }}

    - name: Create Homebrew formulae
      shell: bash
      run: |
        mkdir target/homebrew
        export DARWIN_ARM_TARGET_SHA256=$(openssl dgst -sha256  keboola-cli_darwin_arm64/kbc.zip | cut -f 2 -d ' ' )
        export DARWIN_AMD_TARGET_SHA256=$(openssl dgst -sha256  keboola-cli_darwin_amd64_v1/kbc.zip | cut -f 2 -d ' ' )
        export LINUX_ARM_TARGET_SHA256=$(openssl dgst -sha256   target/*linux_armv6.zip  | cut -f 2 -d ' ' )
        export LINUX_ARM64_TARGET_SHA256=$(openssl dgst -sha256 target/*linux_arm64.zip  | cut -f 2 -d ' ' )
        export LINUX_AMD_TARGET_SHA256=$(openssl dgst -sha256   target/*linux_amd64.zip  | cut -f 2 -d ' ' )
        envsubst < build/package/homebrew/homebrew.template.rb > target/homebrew/keboola-cli.rb
        cat target/homebrew/keboola-cli.rb

    - name: Upload Homebrew formulae
      uses: actions/upload-artifact@v4
      with:
        name: homebrew-formulae
        path: target/homebrew/keboola-cli.rb
        if-no-files-found: error
        retention-days: 1

    - name: Upload Scoop manifest
      uses: actions/upload-artifact@v4
      with:
        name: scoop-manifest
        path: target/scoop/keboola-cli.json
        if-no-files-found: error
        retention-days: 1

    - name: Store release targets
      uses: actions/upload-artifact@v4
      with:
        name: release-targets
        path: |
          target/keboola-cli_${{ inputs.version }}_linux_armv6.zip
          target/keboola-cli_${{ inputs.version }}_linux_amd64.zip
          target/keboola-cli_${{ inputs.version }}_linux_arm64.zip
          target/keboola-cli_${{ inputs.version }}_windows_armv6.zip
          target/keboola-cli_${{ inputs.version }}_windows_amd64.zip
          target/keboola-cli_${{ inputs.version }}_windows_arm64.zip
          target/keboola-cli_darwin_amd64_v1/kbc.zip
          target/keboola-cli_darwin_arm64/kbc.zip
          target/keboola-cli_${{ inputs.version }}_linux_arm64.apk
          target/keboola-cli_${{ inputs.version }}_linux_amd64.apk
          target/keboola-cli_${{ inputs.version }}_linux_armv6.apk
          target/keboola-cli_${{ inputs.version }}_linux_armv6.deb
          target/keboola-cli_${{ inputs.version }}_linux_amd64.deb
          target/keboola-cli_${{ inputs.version }}_linux_arm64.deb
          target/keboola-cli_${{ inputs.version }}_linux_armv6.rpm
          target/keboola-cli_${{ inputs.version }}_linux_amd64.rpm
          target/keboola-cli_${{ inputs.version }}_linux_arm64.rpm
          target/keboola-cli_${{ inputs.version }}_checksums.txt
        if-no-files-found: error
        retention-days: 1
