---
kind: Service
apiVersion: v1
metadata:
  name: stream-api
  namespace: stream
  labels:
    app: stream-api
spec:
  type: NodePort # minikube has no load balancer/external IP by default
  selector:
    app: stream-api
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
