---
apiVersion: v1
kind: ConfigMap
metadata:
  name: templates-api
  namespace: $NAMESPACE
  labels:
    app: templates-api
data:
  sandboxesApiHost: "http://sandboxes-service-api.default.svc.cluster.local)"
  appProxyApiHost: "https://hub.$HOSTNAME_SUFFIX"
  keboolaStack: "$KEBOOLA_STACK"
  keboolaRevision: "$RELEASE_ID"
