---
apiVersion: v1
kind: ConfigMap
metadata:
  name: templates-api
  namespace: $NAMESPACE
  labels:
    app: templates-api
data:
  storageApiHost: "https://connection.$HOSTNAME_SUFFIX"
  templatesApiHost: "https://templates.$HOSTNAME_SUFFIX"
  keboolaStack: "$KEBOOLA_STACK"
  keboolaRevision: "$RELEASE_ID"
