---
apiVersion: v1
kind: ConfigMap
metadata:
  name: buffer-api
  namespace: $NAMESPACE
  labels:
    app: buffer-api
data:
  storageApiHost: "https://connection.$HOSTNAME_SUFFIX"
  bufferApiHost: "https://buffer.$HOSTNAME_SUFFIX"
  keboolaStack: "$KEBOOLA_STACK"
  keboolaRevision: "$RELEASE_ID"
