---
apiVersion: v1
kind: ConfigMap
metadata:
  name: templates-api
  namespace: default
data:
  storageApiUrl: "https://connection.$HOSTNAME_SUFFIX"
  keboolaStack: "$KEBOOLA_STACK"
  keboolaRevision: "$RELEASE_ID"
