root = "."
tmp_dir = "target/.watcher"

[build]
  bin = "./target/buffer/api"
  args_bin = ["--listen-address=http://0.0.0.0:8001"]
  cmd = "make build-buffer-api"
  delay = 2000
  exclude_dir = ["internal/pkg/service/buffer/api/gen"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = ["api", "cmd", "internal", "pkg"]
  include_ext = ["go"]
  kill_delay = 500
  log = "build-errors.log"
  send_interrupt = true
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
