---
# Extends values from the common directory

# Run defragmentation each 2 hours
defrag:
  cronjob:
    schedule: "0 */2 * * *"
    podLabels:
      stream-etcd-client: "true"

preUpgradeJob:
  podLabels:
    stream-etcd-client: "true"
