---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: stream-api
provisioner: kubernetes.io/azure-disk
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  skuName: Premium_LRS
  storageaccounttype: Premium_LRS
  kind: Managed
  cachingmode: None
  fsType: ext4
