name: 'Mount S3 bucket'
description: 'Mount S3 bucket'
runs:
  using: "composite"
  steps:
    - name: Mount S3 bucket
      shell: bash
      run: |
        sudo apt install s3fs
        sudo mkdir $MOUNTED_FOLDER
        sudo chown -R $(id -u):$(id -g) $MOUNTED_FOLDER
        mkdir $HOME/.aws
        printf "[default]\naws_access_key_id=${AWS_ACCESS_KEY_ID}\naws_secret_access_key=${AWS_SECRET_ACCESS_KEY}\n" >> $HOME/.aws/credentials
        [[ -v AWS_SESSION_TOKEN ]] && printf "aws_session_token=${AWS_SESSION_TOKEN}" >> $HOME/.aws/credentials
        chmod 600 ${HOME}/.aws/credentials
        echo -e "\nuser_allow_other\n" | sudo tee -a /etc/fuse.conf
        s3fs -o allow_other -o ahbe_conf="$GITHUB_ACTION_PATH/ahbe.conf" $AWS_BUCKET_NAME $MOUNTED_FOLDER
        ls -alh $MOUNTED_FOLDER
