name: 'Mount S3 bucket'
description: 'Mount S3 bucket'
runs:
  using: "composite"
  steps:
    - name: Mount S3 bucket
      shell: bash
      run: |
        sudo apt install s3fs
        sudo mkdir /s3bucket
        sudo chown -R $(id -u):$(id -g) /s3bucket
        echo $AWS_ACCESS_KEY_ID:$AWS_SECRET_ACCESS_KEY > ${HOME}/.passwd-s3fs
        chmod 600 ${HOME}/.passwd-s3fs
        echo -e "\nuser_allow_other\n" | sudo tee -a /etc/fuse.conf
        s3fs -o allow_other -o ahbe_conf="$GITHUB_ACTION_PATH/ahbe.conf" $AWS_BUCKET_NAME /s3bucket
        ls -alh /s3bucket
