---
kind: Service
apiVersion: v1
metadata:
  name: app-proxy
  namespace: $NAMESPACE
  labels:
    app: app-proxy
spec:
  type: LoadBalancer
  selector:
    app: app-proxy
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
