---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apps-proxy
  namespace: $NAMESPACE
  labels:
    app: apps-proxy
data:
  sandboxesApiHost: "http://sandboxes-service-api.default.svc.cluster.local"
  appsProxyApiHost: "https://hub.$HOSTNAME_SUFFIX"
  keboolaStack: "$KEBOOLA_STACK"
  keboolaRevision: "$RELEASE_ID"
