---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: apps-proxy
  namespace: $NAMESPACE
  labels:
    app: apps-proxy
    releaseId: $RELEASE_ID
spec:
  podSelector:
    matchLabels:
      app: apps-proxy
  policyTypes:
    - Ingress
  ingress:
    # Proxy
    - ports:
        - port: 8000
    # Metrics
    - from:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: datadog
        podSelector:
          matchLabels:
            app: datadog-agent
      ports:
      - port: 9000
