---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: apps-proxy-pdb
  namespace: $NAMESPACE
  labels:
    app: apps-proxy
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: apps-proxy
