name: 'Load build cache'
description: 'Load build cache'
runs:
  using: "composite"
  steps:
    - name: Create directory
      run: mkdir -p /tmp/go-cache
      shell: bash
    - uses: actions/download-artifact@v2
      with:
        name: build-cache
        path: /tmp
    - name: Unzip build cache
      run: unzip -q /tmp/go-cache.zip -d /
      shell: bash
