---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: stream-api
  namespace: stream
  labels:
    app: stream-api
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: stream-api
