openapi: 3.0.3
info:
  title: Templates Service
  description: A service for applying templates to Keboola projects
  version: "1.0"
servers:
- url: https://templates.{stack}
  variables:
    stack:
      enum:
      - keboola.com
      - eu-central-1.keboola.com
      - north-europe.azure.keboola.com
      default: keboola.com
paths:
  /:
    get:
      tags:
      - templates
      summary: index-root templates
      operationId: templates#index-root
      responses:
        "301":
          description: Moved Permanently response.
  /v1:
    get:
      tags:
      - templates
      summary: index templates
      operationId: templates#index
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Index'
              example:
                api: templates
                documentation: https://templates.keboola.com/v1/documentation
  /v1/documentation/openapi.json:
    get:
      tags:
      - templates
      summary: Download gen/openapi.json
      operationId: templates#/v1/documentation/openapi.json
      responses:
        "200":
          description: File downloaded
  /v1/documentation/openapi.yaml:
    get:
      tags:
      - templates
      summary: Download gen/openapi.yaml
      operationId: templates#/v1/documentation/openapi.yaml
      responses:
        "200":
          description: File downloaded
  /v1/documentation/openapi3.json:
    get:
      tags:
      - templates
      summary: Download gen/openapi3.json
      operationId: templates#/v1/documentation/openapi3.json
      responses:
        "200":
          description: File downloaded
  /v1/documentation/openapi3.yaml:
    get:
      tags:
      - templates
      summary: Download gen/openapi3.yaml
      operationId: templates#/v1/documentation/openapi3.yaml
      responses:
        "200":
          description: File downloaded
  /v1/health-check:
    get:
      tags:
      - templates
      summary: health-check templates
      operationId: templates#health-check
      responses:
        "200":
          description: OK response.
components:
  schemas:
    Index:
      type: object
      properties:
        api:
          type: string
          description: Name of the API
          example: templates
        documentation:
          type: string
          description: Url of the API documentation
          example: https://templates.keboola.com/v1/documentation
      example:
        api: templates
        documentation: https://templates.keboola.com/v1/documentation
      required:
      - api
      - documentation
tags:
- name: templates
  description: Service for applying templates to Keboola projects
