global:
  scrape_interval: 10s
scrape_configs:
 - job_name: prometheus
   static_configs:
    - targets:
       - 'prometheus:9090'
 - job_name: templatesAPI
   static_configs:
    - targets:
       - 'dev:9000'
 - job_name: streamAPI
   static_configs:
    - targets:
       - 'dev:9001'
 - job_name: AppsProxy
   static_configs:
    - targets:
       - 'dev:9002'
