---
kind: Service
apiVersion: v1
metadata:
  name: stream-http-source
  namespace: $NAMESPACE
  labels:
    app: stream-http-source
spec:
  type: NodePort # minikube has no load balancer/external IP by default
  selector:
    app: stream-http-source
  ports:
    - port: 80
      targetPort: 7000
      protocol: TCP
      name: http
