version: '3'
services:
  deb:
    image: keboolabot/keboola-as-code-index-deb
    build:
      context: .
      dockerfile: ./Dockerfile-deb
    volumes:
      - $PACKAGES_DIR:/packages
      - ./index_apt.sh:/scripts/index_deb.sh
    environment:
      - DEB_KEY_PUBLIC
      - DEB_KEY_PRIVATE

  rpm:
    image: keboolabot/keboola-as-code-index-rpm
    build:
      context: .
      dockerfile: ./Dockerfile-rpm
    volumes:
      - $PACKAGES_DIR:/packages
      - ./index_rpm.sh:/scripts/index_rpm.sh
    environment:
      - RPM_KEY_PUBLIC
      - RPM_KEY_PRIVATE

  apk:
    image: keboolabot/keboola-as-code-index-apk
    build:
      context: .
      dockerfile: ./Dockerfile-apk
    volumes:
      - $PACKAGES_DIR:/packages
      - ./index_apk.sh:/scripts/index_apk.sh
    environment:
      - APK_KEY_PUBLIC
      - APK_KEY_PRIVATE
