version: '3'
services:
  apt:
    image: keboolabot/keboola-as-code-index-apt
    build:
      context: .
      dockerfile: ./Dockerfile-apt
    volumes:
      - $PACKAGES_DIR:/packages
      - ./index_apt.sh:/scripts/index_apt.sh
    environment:
      - GPG_PUBLIC
      - GPG_PRIVATE

  rpm:
    image: keboolabot/keboola-as-code-index-rpm
    build:
      context: .
      dockerfile: ./Dockerfile-rpm
    volumes:
      - $PACKAGES_DIR:/packages
      - ./index_rpm.sh:/scripts/index_rpm.sh
    environment:
      - GPG_PUBLIC
      - GPG_PRIVATE

  apk:
    image: keboolabot/keboola-as-code-index-apk
    build:
      context: .
      dockerfile: ./Dockerfile-apk
    volumes:
      - $PACKAGES_DIR:/packages
      - ./index_apk.sh:/scripts/index_apk.sh
    environment:
      - ALPINE_PRIVATE_KEY
      - ALPINE_PUBLIC_KEY
