name: 'Load Go cache'
description: 'Load Go build cache'
inputs:
  key:
    description: Cache key
    required: true
runs:
  using: "composite"
  steps:
    - name: Use GNU tar instead BSD tar
      if: runner.os == 'Windows'
      shell: bash
      run: echo 'C:\Program Files\Git\usr\bin' >> $GITHUB_PATH

    - name: Load Go cache
      uses: actions/cache@v3
      with:
        path: |
          ~/go/pkg
          ~\go\pkg
          ~/go/bin
          ~\go\bin
          ~/.cache/golangci-lint
          ~/Library/Caches/golangci-lint
          ~\AppData\Local\golangci-lint
        key: ${{ runner.os }}-go-${{ env.GO_VERSION }}-v5-${{ inputs.key }}-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-${{ env.GO_VERSION }}-v5-
          ${{ runner.os }}-go-${{ env.GO_VERSION }}-v5-${{ inputs.key }}-
