openapi: 3.0.3
info:
  title: Templates Service
  description: A service for applying templates to Keboola projects
  version: "1.0"
servers:
- url: http://localhost:8000
paths:
  /:
    get:
      tags:
      - templates
      summary: index templates
      operationId: templates#index
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Index'
              example:
                api: Corrupti nisi cumque.
                documentation: Est aliquid nihil praesentium similique autem.
  /health-check:
    get:
      tags:
      - templates
      summary: health-check templates
      operationId: templates#health-check
      responses:
        "200":
          description: OK response.
  /openapi.json:
    get:
      tags:
      - templates
      summary: Download ./gen/http/openapi.json
      operationId: templates#/openapi.json
      responses:
        "200":
          description: File downloaded
components:
  schemas:
    Index:
      type: object
      properties:
        api:
          type: string
          example: Exercitationem assumenda quo quidem sapiente harum consequuntur.
        documentation:
          type: string
          example: Sed dolores sunt dolorem.
      example:
        api: Quas voluptatum.
        documentation: Eius adipisci possimus dicta.
tags:
- name: templates
  description: Service for applying templates to Keboola projects
