swagger: "2.0"
info:
  title: Templates Service
  description: A service for applying templates to Keboola projects
  version: ""
host: localhost:8000
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /:
    get:
      tags:
      - templates
      summary: index templates
      operationId: templates#index
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/TemplatesIndexResponseBody'
      schemes:
      - http
  /health-check:
    get:
      tags:
      - templates
      summary: health-check templates
      operationId: templates#health-check
      responses:
        "200":
          description: OK response.
      schemes:
      - http
  /openapi.json:
    get:
      tags:
      - templates
      summary: Download ./gen/http/openapi.json
      operationId: templates#/openapi.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
definitions:
  TemplatesIndexResponseBody:
    title: 'Mediatype identifier: application/vnd.templates.index; view=default'
    type: object
    properties:
      api:
        type: string
        example: Fugit numquam quidem.
      documentation:
        type: string
        example: Accusantium voluptas.
    description: IndexResponseBody result type (default view)
    example:
      api: Consequatur qui est ipsam provident omnis corporis.
      documentation: Incidunt voluptas deserunt rem sapiente.
