name: GitHub Actions
on: [ push ]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Print Docker version
        run: |
          docker -v
      - name: Set version
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]];
          then
            export TARGET_VERSION=${GITHUB_REF/refs\/tags\//}
          else
            export TARGET_VERSION="dev"
          fi
          echo ${TARGET_VERSION}
      - name: Build dev Docker image
        run: |
          docker-compose build
      - name: Compile
        run: |
          docker-compose run --rm dev make build
      - name: Cross compile
        run: |
          docker-compose run --rm dev make build-cross
      - name: Upload binaries to release
        if: startsWith(github.ref, 'refs/tags/')
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/archive/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
