name: GitHub Actions
on: [push]
env:
  TEST_PROJECT_ID: 8614
  TEST_PROJECT_NAME: keboola-as-code-tests
  TEST_KBC_STORAGE_API_HOST: connection.keboola.com
  TEST_KBC_STORAGE_API_TOKEN: ${{ secrets.TEST_KBC_STORAGE_API_TOKEN }}
  TEST_KBC_STORAGE_API_TOKEN_MASTER: ${{ secrets.TEST_KBC_STORAGE_API_TOKEN_MASTER }}
  TEST_KBC_STORAGE_API_TOKEN_EXPIRED: ${{ secrets.TEST_KBC_STORAGE_API_TOKEN_EXPIRED }}
jobs:
  Build:
    concurrency: ci # only one parallel job allowed - used shared testing project
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Print Docker version
        run: |
          docker -v
      - name: Set version
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]];
          then
            export TARGET_VERSION=${GITHUB_REF/refs\/tags\//}
          else
            export TARGET_VERSION="dev"
          fi
          echo ${TARGET_VERSION}
          echo "TARGET_VERSION=${TARGET_VERSION}" >> $GITHUB_ENV
      - name: Build dev Docker image
        run: |
          docker-compose build
      #      - name: Tests
      #        run: |
      #          docker-compose run --rm -u "$UID:$GID" dev make tests
      - name: Compile
        run: |
          docker-compose run --rm -u "$UID:$GID" dev make build
      - name: Compile and Release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          docker-compose run --rm -u "$UID:$GID" -e GITHUB_TOKEN -e TARGET_VERSION dev make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
