name: 'Release: Buffer API'

on:
  push:
    tags:
      - 'buffer-api-v**'

env:
  IMAGE_NAME_API: "keboola/buffer-api"
  IMAGE_NAME_WORKER: "keboola/buffer-worker"
  IMAGE_TAG: ${{ github.ref_name }}
  ECR_REGION: "us-east-1"
  ECR_REPOSITORY: "keboola/buffer-api"
  ECR_PUSH_ROLE: "TODO"
  ACR_REPOSITORY: "buffer-api"
  ACR_REGISTRY: "keboola.azurecr.io"
  ACR_USERNAME: "buffer-api-push"

jobs:
  test-lint:
    name: "Lint"
    secrets: inherit
    uses: ./.github/workflows/test-lint.yml
  test-unit:
    name: "Unit Tests"
    secrets: inherit
    uses: ./.github/workflows/test-unit.yml
  test-e2e-service-templates:
    name: "E2E: Templates"
    secrets: inherit
    uses: ./.github/workflows/test-e2e-templates-api.yml
  test-k8s-service-templates:
    name: "K8S: Templates"
    secrets: inherit
    uses: ./.github/workflows/test-k8s-templates-api.yml
  build-and-push-api-image:
    name: "Build & Push API Image"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    needs:
      - test-lint
      - test-unit
      - test-e2e-service-templates
      - test-k8s-service-templates
    steps:
      - name: TODO
        run: echo "TODO"
