name: 'Provisioning: Templates API'
on:
  pull_request:
    branches:
      - main
    paths:
      - provisioning/templates-api/**

env:
  MINIKUBE_PROFILE: templates-api

defaults:
  run:
    working-directory: provisioning/templates-api

jobs:
  test:
    name: 'Test'
    runs-on: ubuntu-latest
    steps:
      - name: Start MiniKube
        uses: medyagh/setup-minikube@latest
        with:
          wait: "apiserver,system_pods,default_sa,apps_running,node_ready,kubelet"
          # https://github.com/kubernetes/minikube/issues/15173
          kubernetes-version: v1.24.7
          # Enable Network Policies support
          network-plugin: cni
          cni: calico
      - name: Checkout BASE branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.ref }}
      - name: Deploy the previous version, from the BASE branch
        run: ./deploy_local.sh
      - name: Checkout HEAD branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Deploy the new version, from the HEAD branch
        run: ./deploy_local.sh
      - name: Check deployment of the etcd
        run: kubectl rollout status sts/templates-api-etcd --namespace templates-api
      - name: Check deployment of the API
        run: kubectl rollout status deployment/templates-api --namespace templates-api
      - name: Check API response
        run: |
          curl --fail -L -s "$(minikube service --url --namespace templates-api templates-api)"
