name: "E2E: Buffer"

on:
  workflow_call:

env:
  GO_VERSION: 1.22.2
  TEST_PARALLELISM: 4
  TEST_PARALLELISM_PKG: 1
  TEST_KBC_PROJECTS: |
    [
      {"host":"connection.keboola.com","project":8769,"stagingStorage":"s3","backend":"snowflake","token":"${{ secrets.TEST_KBC_PROJECT_8769_TOKEN }}"},
      {"host":"connection.keboola.com","project":8775,"stagingStorage":"s3","backend":"snowflake","token":"${{ secrets.TEST_KBC_PROJECT_8775_TOKEN }}"},
      {"host":"connection.europe-west3.gcp.keboola.com","project":43,"stagingStorage":"gcs","backend":"bigquery","token":"${{ secrets.TEST_KBC_PROJECT_43_TOKEN }}"},
      {"host":"connection.europe-west3.gcp.keboola.com","project":44,"stagingStorage":"gcs","backend":"bigquery","token":"${{ secrets.TEST_KBC_PROJECT_44_TOKEN }}"},
      {"host":"connection.north-europe.azure.keboola.com","project":10900,"stagingStorage":"abs","backend":"snowflake","token":"${{ secrets.TEST_KBC_PROJECT_10900_TOKEN }}"},
      {"host":"connection.north-europe.azure.keboola.com","project":10906,"stagingStorage":"abs","backend":"snowflake","token":"${{ secrets.TEST_KBC_PROJECT_10906_TOKEN }}"}
    ]

jobs:
  test:
    name: test
    concurrency:
      group: tests-e2e-service-buffer
      cancel-in-progress: false
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Setup line endings
        run: git config --global core.autocrlf false

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Load Go cache
        uses: ./.github/actions/go-cache
        with:
          key: e2e

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false

      - name: Install tools
        run: . ./scripts/tools.sh
        shell: bash

      - name: Start etcd database
        run: |
          set -Eeuo pipefail
          docker compose run -d --rm --publish 2379:2379 etcd
          sudo echo "127.0.0.1 etcd" | sudo tee -a /etc/hosts

      - name: Run API E2E tests
        run: make tests-stream-api
        shell: bash
        env:
          STREAM_ETCD_ENDPOINT: etcd:2379
          STREAM_ETCD_USERNAME: root
          STREAM_ETCD_PASSWORD: toor
          STREAM_ETCD_NAMESPACE: stream-api

      - name: Validate OpenAPI3 definition
        uses: char0n/swagger-editor-validate@b642f037ac53c392f9c8d781c369ce129684e93e
        with:
          definition-file: internal/pkg/service/stream/api/openapi/openapi3.yaml

