name: 'E2E: Buffer'

on:
  workflow_call:

env:
  GO_VERSION: 1.19
  TEST_PARALLELISM: 4
  TEST_PARALLELISM_PKG: 1
  TEST_KBC_PROJECTS: |
    [
      {"host":"connection.keboola.com","project":8769,"stagingStorage":"s3","token":"${{ secrets.TEST_KBC_PROJECT_8769_TOKEN }}"},
      {"host":"connection.keboola.com","project":8775,"stagingStorage":"s3","token":"${{ secrets.TEST_KBC_PROJECT_8775_TOKEN }}"},
      {"host":"connection.north-europe.azure.keboola.com","project":10900,"stagingStorage":"abs","token":"${{ secrets.TEST_KBC_PROJECT_10900_TOKEN }}"},
      {"host":"connection.north-europe.azure.keboola.com","project":10906,"stagingStorage":"abs","token":"${{ secrets.TEST_KBC_PROJECT_10906_TOKEN }}"}
    ]

jobs:
  test:
    name: test
    concurrency:
      group: tests-e2e-service-buffer
      cancel-in-progress: false
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Setup line endings
        run: git config --global core.autocrlf false

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Load Go cache
        uses: ./.github/actions/go-cache
        with:
          key: e2e

      - name: Install tools
        run: . ./scripts/tools.sh
        shell: bash

      - name: Run tests
        run: make tests-buffer-api
        shell: bash
