name: "E2E Tests: CLI"

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: false
      without-cache:
        type: boolean
        default: false
        required: false

env:
  TEST_PARALLELISM: 16
  TEST_PARALLELISM_PKG: 1

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  test:
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: linux
            os: ubuntu-latest
          - name: mac-os
            os: macos-latest
          - name: windows
            os: windows-2022
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup line endings
        run: git config --global core.autocrlf false

      - name: Change default TEST_COVERAGE when on main branch
        if: github.ref == 'refs/heads/main'
        run: echo "TEST_COVERAGE=true" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go, tools and caching
        uses: ./.github/actions/go-setup
        with:
          build-type: e2e-tests-cli
          go-version: ${{ vars.GO_VERSION }}
          without-cache: ${{ inputs.without-cache }}
          cache-s3-bucket: ${{ vars.CACHE_S3_BUCKET }}

      - name: Set TEST_KBC_PROJECTS_FILE entries
        uses: ./.github/actions/export-kbc-projects
        with:
          secrets: ${{ toJSON(secrets) }}

      - name: Run tests
        run: |
          set -eo pipefail
          
          if [ "$RUNNER_OS" == "Windows" ]; then
            export TEST_BINARY_CLI="${{ runner.temp }}\test-build-cli.exe"
          else
            export TEST_BINARY_CLI="${{ runner.temp }}/test-build-cli"
          fi
          
          # Build binary for test without external inputs
          env -i \
            TERM="$TERM" \
            HOME="$HOME" \
            PATH="$PATH" \
            APPDATA="$APPDATA" \
            BUILD_TARGET_PATH="$TEST_BINARY_CLI" \
            CLI_BUILD_DATE="-" \
            CLI_BUILD_GIT_COMMIT="-" \
          make build-local
          touch -d '1970-01-01T00:00:01' "$TEST_BINARY_CLI"
          
          # Calculate binary hash, it invalidates tests cache
          export TEST_BINARY_CLI_HASH=`cat "$TEST_BINARY_CLI" | $MD5_COMMAND | cut -d " " -f1`
          echo "Binary hash: $TEST_BINARY_CLI_HASH"
          
          # ENVs can affect test caching, make sure to only run tests with expected ENVs
          env -i \
            TERM="$TERM" \
            HOME="$HOME" \
            PATH="$PATH" \
            APPDATA="$APPDATA" \
            TEST_BINARY_CLI="$TEST_BINARY_CLI" \
            TEST_BINARY_CLI_HASH="$TEST_BINARY_CLI_HASH" \
            TEST_PARALLELISM="$TEST_PARALLELISM" \
            TEST_PARALLELISM_PKG="$TEST_PARALLELISM_PKG" \
            TEST_COVERAGE="false" \
            TEST_CREATE_OUT_DIR="false" \
            TEST_KBC_PROJECTS_LOCK_HOST="$TEST_KBC_PROJECTS_LOCK_HOST" \
            TEST_KBC_PROJECTS_LOCK_PASSWORD="$TEST_KBC_PROJECTS_LOCK_PASSWORD" \
            TEST_KBC_PROJECTS_FILE="$TEST_KBC_PROJECTS_FILE" \
          make tests-cli
        shell: bash
        env:
          VERSION: ${{ inputs.version }}
          TEST_KBC_PROJECTS_LOCK_HOST: ${{ vars.TEST_KBC_PROJECTS_LOCK_HOST }}
          TEST_KBC_PROJECTS_LOCK_PASSWORD: ${{ secrets.TEST_KBC_PROJECTS_LOCK_PASSWORD }}
          TEST_KBC_PROJECTS_FILE: '${{ github.workspace }}/${{ vars.TEST_KBC_PROJECTS_FILE }}'
