name: "E2E Tests: CLI"

on:
  workflow_call:
    inputs:
      version:
        type: string
        required: false

env:
  GO_VERSION: 1.22.2
  TEST_PARALLELISM: 16
  TEST_PARALLELISM_PKG: 1
  # Temporary removed project: https://keboolaglobal.slack.com/archives/C055HSMKX51/p1714024266416349
#  { "host": "connection.north-europe.azure.keboola.com","project": 10890,"stagingStorage": "abs","backend": "snowflake","token": "$TEST_KBC_PROJECT_10890_TOKEN", "legacyTransformation": true },
#  { "host": "connection.north-europe.azure.keboola.com","project": 10891,"stagingStorage": "abs","backend": "snowflake","token": "$TEST_KBC_PROJECT_10891_TOKEN", "legacyTransformation": true }
#  { "host":"connection.north-europe.azure.keboola.com","project":10892,"stagingStorage":"abs","backend":"snowflake","token":"$TEST_KBC_PROJECT_10892_TOKEN", "legacyTransformation": true}
#  {"host":"connection.north-europe.azure.keboola.com","project":10898,"stagingStorage":"abs","backend":"snowflake","token":"$TEST_KBC_PROJECT_10898_TOKEN", "legacyTransformation": true},

jobs:
  test:
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: linux
            os: ubuntu-latest
          - name: mac-os
            os: macos-latest
          - name: windows
            os: windows-2022
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup line endings
        run: git config --global core.autocrlf false

      - name: Evaluate environment
        run: echo "TEST_KBC_PROJECTS=$(echo $TEST_KBC_PROJECTS | envsubst)" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Load Go cache
        uses: ./.github/actions/go-cache
        with:
          key: e2e

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false

      - name: Install tools
        run: . ./scripts/tools.sh
        shell: bash

      - name: Run tests
        run: make tests-cli
        shell: bash
        env:
          VERSION: ${{ inputs.version }}
          TEST_KBC_PROJECTS_LOCK_HOST: ${{ vars.TEST_KBC_PROJECTS_LOCK_HOST }}
          TEST_KBC_PROJECTS_LOCK_PASSWORD: ${{ secrets.TEST_KBC_PROJECTS_LOCK_PASSWORD }}
