---
kind: Job
apiVersion: batch/v1
metadata:
  name: benchmark
  namespace: stream-benchmark
  labels:
    app: stream-benchmark
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: load-test
        stream-etcd-client: "true"
        tags.datadoghq.com/env: "$KEBOOLA_STACK"
        tags.datadoghq.com/service: "load-test"
        tags.datadoghq.com/version: "stream-benchmark"
      annotations:
        log: "true"
    spec:
      terminationGracePeriodSeconds: 300
      restartPolicy: Never
      containers:
        - name: benchmark
          image: docker.io/keboolabot/stream-benchmark:latest
          imagePullPolicy: Always
          command: ["k6"]
          args: ["run", "--out", "output-statsd", "/scripts/k6/stream-api/static.js"]
          resources:
            requests:
              cpu: "1"
              memory: "4Gi"
          env:
            - name: API_HOST
              value: "http://stream-api.stream.svc.cluster.local"
            - name: API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: benchmark
                  key: api-token
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_STATSD_PORT
              value: "8125"
            - name: K6_STATSD_ADDR
              value: $(DD_AGENT_HOST):$(DD_STATSD_PORT)
            - name: K6_STATSD_NAMESPACE
              value: "k6."
            - name: K6_STATSD_PUSH_INTERVAL
              value: "5s"
            - name: K6_STATSD_BUFFER_SIZE
              value: "1000"
            - name: K6_STATSD_ENABLE_TAGS
              value: "true"
            - name: K6_PARALLEL_REQS_PER_USER
              value: "10"
            - name: K6_SCENARIO
              value: "ramping"
            - name: K6_CONST_VIRTUAL_USERS
              value: "1000"
            - name: K6_CONST_TOTAL_REQUESTS
              value: "1000000"
            - name: K6_CONST_TIMEOUT
              value: "20m"
            - name: K6_RAMPING_MAX_VIRTUAL_USERS
              value: "100"
            - name: K6_RAMPING_UP_DURATION
              value: "1m"
            - name: K6_RAMPING_STABLE_DURATION
              value: "2m"
            - name: K6_RAMPING_DOWN_DURATION
              value: "1m"
      tolerations:
        - key: app
          operator: Exists
          effect: NoSchedule
      nodeSelector:
        nodepool: main
